import SearchIcon from "./assets/icons/web/icons/landing/mobile/1.png";
import SelectIcon from "./assets/icons/web/1.svg";
import StandOutIcon from "./assets/icons/web/2.svg";
import Picture1 from './assets/Rectangle-124.png'
import Picture2 from './assets/Rectangle-125.png'
import Picture3 from './assets/Rectangle-126.png'
import Picture4 from './assets/Rectangle-127.png'

export default [
    {
        id: "line1",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line2",
        data: "coziness building for tomorrow"
    },
    {
        id: "line3",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line4",
        data: "Review the facts cool is the best."
    },
    {
        id: "line5",
        data: "Review the facts cool is the best."
    },
    {
        id: "line6",
        data: "coziness building for tomorrow"
    },
    {
        id: "line7",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line8",
        data: "coziness building for tomorrow"
    },
    {
        id: "line9",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line10",
        data: "coziness building for tomorrow"
    },
    {
        id: "line11",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line12",
        data: "coziness building for tomorrow"
    },
    {
        id: "line13",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line14",
        data: "coziness building for tomorrow"
    },
    {
        id: "line15",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line16",
        data: "coziness building for tomorrow"
    },
    {
        id: "line17",
        data: "There is no Sore it will Not Heal, No cool it will not Subdue."
    },
    {
        id: "line18",
        data: "coziness building for tomorrow"
    }
]

export const productDetails = [
    { id: "product1", title: "Privacy Policy Generator", description: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.", image: Picture1 },
    { id: "product2", title: "Terms & Conditions Generator", description: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.", image: Picture2 },
    { id: "product3", title: "Domain Name Generator", description: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.", image: Picture3 },
    { id: "product4", title: "Invoice Generator", description: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.", image: Picture4 }
]

export const cardInfo = [
    { id: "pic1", path: SearchIcon, alt: "search_icon", headingText: "Search", content: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen." },
    { id: "pic2", path: SelectIcon, alt: "select_icon", headingText: "Select", content: "Choose from thousands of options generated by the slogan maker that fit your needs." },
    { id: "pic3", path: StandOutIcon, alt: "standout_icon", headingText: "Stand Out", content: "Congrats on your new slogan. It's time to win the world!" }
]

export interface IFooterLinks {
    id: string,
    href: string,
    name: string,
    meta?: string
}

export const FooterLinks: IFooterLinks[] = [
    { id: 'link1', href: '#', name: 'Contact' },
    { id: 'link2', href: '#', name: 'Tutorial' },
    { id: 'link3', href: '#', name: 'Privacy' },
    { id: 'link4', href: '#', name: 'About' },
    { id: 'link5', href: '#', name: 'Facebook' },
    { id: 'link6', href: '#', name: "FAQ's" },
    { id: 'link7', href: '#', name: 'Blog' },
    { id: 'link8', href: '#', name: 'Banned Items' },
    { id: 'link9', href: '#', name: 'Jobs', meta: '3' },
    { id: 'link10', href: '#', name: 'Twitter' },
    { id: 'link11', href: '#', name: 'LinkedIn' },
]